apiVersion: v1
kind: Service
metadata:
  name: logbook
  labels:
    app: logbook
spec:
  ports:
  - port: 3000
    name: web
  type: NodePort
  selector:
    app: logbook
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logbook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logbook
    spec:
      containers:
      - name: logbook
        image: cedbossneo/logbook
        command:
          - logbook
          - --rabbitmq-uri=amqp://user:password@host:5672/
        ports:
        - containerPort: 3000
          name: web
