apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
  replicas: 1
  selector:
    db: rethinkdb
    role: admin
  template:
    metadata:
      labels:
        db: rethinkdb
        role: admin
    spec:
      containers:
      - image: cedbossneo/rethinkdb-kubernetes:2.3.4
        imagePullPolicy: Always
        name: rethinkdb
        env:
        - name: PROXY
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RETHINK_CLUSTER
          value: rethinkdb-cluster
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        emptyDir: {}