apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-driver
spec:
  ports:
    - port: 28015
      targetPort: driver-port
  selector:
    db: rethinkdb
    role: proxy