version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  twitter-bot:
    build:
      context: .
    image: xebiafrance/xebicon-twitter
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBIT_EXCHANGE: xebiconExchange
