apiVersion: v1
kind: Service
metadata:
  labels:
    component: redis
    display: database
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    component: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      name: redis
      labels:
        component: redis
        display: database
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - name: main
          containerPort: 6379
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
      - name: data
        rbd:
          monitors:
          - ceph-mon.ceph:6789
          user: admin
          image: redis
          pool: rbd
          secretRef:
            name: ceph-client-key